feeder: dataset.dataset.BaseFeeder
# phase: train
phase: test
dataset: EvCSLRDataset
num_epoch: 1000
work_dir: ./work_dir/test_results/
batch_size: 1
random_seed: 0
test_batch_size: 1
num_worker: 10
device: 0
log_interval: 10000
eval_interval: 1
save_interval: 1
# python in default
evaluate_tool: sclite
loss_weights:
  ConvCTC: 1.0
  SeqCTC: 1.0

  Cu: 0.001
  Cp: 0.001

load_weights: './checkpoint.pt'

optimizer_args:
  optimizer: Adam 
  base_lr: 0.0001
  step: [40, 80]
  learning_ratio: 1
  weight_decay: 0.0001
  start_epoch: 51
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
decode_mode: beam
model_args:
  num_classes: 424
  c2d_type: resnet18 #resnet18, mobilenet_v2, squeezenet1_1, shufflenet_v2_x1_0, efficientnet_b1, mnasnet1_0, regnet_y_800mf, vgg16_bn, vgg11_bn, regnet_x_800mf, regnet_x_400mf, densenet121, regnet_y_1_6gf
  conv_type: 2
  use_bn: 1
  # SMKD
  share_classifier: True
  weight_norm: True
